name: Update arXiv Page

on:
  schedule:
    - cron: '0 3 * * *'  # Every day at 03:00 UTC
  workflow_dispatch:      # Manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install feedparser

      - name: Generate arXiv HTML
        run: python generate_arxiv_page.py

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add arxiv.html
          git commit -m "Auto-update arXiv page"
          git push
